### ISSUE TITLE
First set of values passed to pool work. Second set give string formatting error.

### ISSUE THREAD

**Issue by jackjt8** [jackjt8/EQPB_2017#10]
```
Traceback (most recent call last):
  File "D:\jackj\Documents\GitHub\EQPB_2017\auto2.py", line 31, in <module>
    main()
  File "D:\jackj\Documents\GitHub\EQPB_2017\auto2.py", line 23, in main
    tc.runtc([400], alt2test, L_thres) # intalt needs to be an array as it's treated like alt2test.
  File "D:\jackj\Documents\GitHub\EQPB_2017\tc_full.py", line 44, in runtc
    self.mthandler(this_sat, dday, ls, satalt, bcoord, indices, eq_datetimes, L_shells, L_thres, intalt)
  File "D:\jackj\Documents\GitHub\EQPB_2017\tc_full.py", line 139, in mthandler
    pool.map(self.tc_fw, repeat(self.localpath), repeat(this_sat), repeat(dday), repeat(ls), repeat(satalt),repeat(bcoord), repeat(indices), repeat(eq_datetimes), L_thres, repeat(L_shells[0]), repeat(alt2test[0]))
  File "C:\Anaconda35\envs\py27\lib\site-packages\pathos\multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "C:\Anaconda35\envs\py27\lib\site-packages\multiprocess\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Anaconda35\envs\py27\lib\site-packages\multiprocess\pool.py", line 567, in get
    raise self._value
TypeError: not all arguments converted during string formatting
```

The first set of values sent to the pools are correct, but it seems the second set have problems. Printing out `this_sat, lthres, alt, len(indices)*len(L_shells)` works up til the first test of the second batch where it prints this_sat then fails. `L_thres` prints out just fine so I'm not sure why it's failing here. Might need to move to `str.format()` to fix this issue, but it might be a problem with pool.

**Comment by jackjt8** [comment]
I just noticed something.. the print that occurs when the pool finishes does not show up. I'm guessing the problem is here and not elsewhere...

**Comment by jackjt8** [comment]
Issue found - Line 198 string formatting had 3 %s and 4 args. Cleaned up and fixed this issue.
